name: Deploy Docusaurus to VPS

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Prepare VPS directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directory if it doesn't exist
            sudo mkdir -p /var/www/kemet-lang.org
            # Give your user ownership temporarily for rsync
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/kemet-lang.org

      - name: Copy files to VPS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          rsync -avz --delete -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            build/ \
            ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/var/www/kemet-lang.org/
          rm -f private_key

      - name: Set final permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set ownership to web server user
            sudo chown -R www-data:www-data /var/www/kemet-lang.org
            sudo chmod -R 755 /var/www/kemet-lang.org